vscode:
  extensions:
    - vscjava.vscode-spring-initializr

tasks:
  - name: Intall java 21
    before: sdk install java 21.0.5-tem < /dev/null

  - name: Launch docker postgres
    init: |
      docker run --name spring-postgres-container -e POSTGRES_USER=bobo -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres:alpine
    command: |
      sleep 10
      docker exec -i spring-postgres-container psql -U bobo < init.sql
